### ISSUE TITLE
Enable full linting support for Python 3.14

### ISSUE THREAD

**Issue by dmayo3** [dmayo3/mocksafe#99]
## Summary

Currently, Python 3.14 support in CI skips linting due to compatibility issues with static analysis tools. This issue tracks enabling full linting support for Python 3.14.

## Background

Python 3.14 support was added in PR #98, but linting had to be disabled due to tool compatibility issues. The current workaround (added in commit `4124cd5`) conditionally runs only the core test suite (`tox -e py314`) for Python 3.14, while other versions run the full suite including linting.

### 1. **flake8** - Token API Changes
- **Error**: `AttributeError: module 'tokenize' has no attribute 'TSTRING_START'. Did you mean: 'FSTRING_START'?`
- **Cause**: Python 3.14 renamed tokenize constants ([Python 3.14 What's New](https://docs.python.org/dev/whatsnew/3.14.html))
- **Status**: Needs flake8 update

### 2. **pylint/astroid** - AST Changes  
- **Error**: Various astroid inference crashes due to Python 3.14 AST changes
- **Cause**: Python 3.14 removed deprecated AST nodes (`ast.Str`, `ast.Num`, etc.) in favor of `ast.Constant`
- **Status**: astroid 4.0.0+ has basic Python 3.14 support, but may need newer versions

## Affected Workflows

- `.github/workflows/mocksafe.yml` (lines 40-46)
- Conditional logic that runs different tox environments based on Python version

### Option 1: Wait for Tool Updates (Recommended)
- Monitor pylint/astroid and flake8 releases for Python 3.14 support
- Update tool versions in `pyproject.toml` when available
- Remove conditional workflow logic

### Option 2: Switch to Modern Tools
- **ruff**: Modern, fast linter with better Python 3.14 support
- **pros**: Much faster, actively maintained, good Python 3.14 support
- **cons**: Different rule set, migration effort

### Option 3: Selective Tool Updates
- Keep working tools (e.g., mypy, black)
- Replace problematic tools (flake8 → ruff)
- Hybrid approach

## Acceptance Criteria

- [ ] All linting tools work with Python 3.14.0 (final release)
- [ ] Remove conditional logic from GitHub Actions workflow
- [ ] All CI jobs (including Python 3.14) run full test suite with linting
- [ ] Update documentation if tool changes are made

## Timeline Considerations

- **Python 3.14.0 GA**: Expected ~October 2025
- **Tool Support**: Usually lags 1-3 months after Python GA
- **Target**: v0.12 beta (due Nov 30, 2025) seems reasonable

## Related

- PR #98: Add support for Python 3.14
- Commit `4124cd5`: Skip linting for Python 3.14 due to tool compatibility

## References

- [Python 3.14 What's New](https://docs.python.org/dev/whatsnew/3.14.html)
- [Python 3.14 Readiness Tracker](https://pyreadiness.org/3.14/)
- [astroid changelog](https://pylint.pycqa.org/projects/astroid/en/latest/changelog.html)
